version: '3.8'

services:
  database:
    image: postgres:15
    container_name: sports_analytics_db
    environment:
      POSTGRES_DB: sports_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sports_analytics"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: sports_analytics_backend
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_DB: sports_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      CATAPULT_API_TOKEN: ${CATAPULT_API_TOKEN}
      APP_ENV: development
      DEBUG: "true"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: